# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample_message.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, '', 'sample_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14sample_message.proto":\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x10\n\x08zip_code\x18\x03 \x01(\t"B\n\x07\x43ontact\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x19\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x08.Address"\xda\x01\n\rSampleMessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nitem_count\x18\x03 \x01(\x05\x12\x17\n\x06status\x18\x04 \x01(\x0e\x32\x07.Status\x12\x19\n\x0c\x64isplay_name\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0epriority_level\x18\x06 \x01(\x05H\x01\x88\x01\x01\x12\x19\n\x07\x63ontact\x18\x07 \x01(\x0b\x32\x08.ContactB\x0f\n\r_display_nameB\x11\n\x0f_priority_level*\\\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n\x0eSTATUS_PENDING\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'sample_message_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_STATUS']._serialized_start = 373
    _globals['_STATUS']._serialized_end = 465
    _globals['_ADDRESS']._serialized_start = 24
    _globals['_ADDRESS']._serialized_end = 82
    _globals['_CONTACT']._serialized_start = 84
    _globals['_CONTACT']._serialized_end = 150
    _globals['_SAMPLEMESSAGE']._serialized_start = 153
    _globals['_SAMPLEMESSAGE']._serialized_end = 371
# @@protoc_insertion_point(module_scope)
