# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample_message.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 1, '', 'sample_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14sample_message.proto"\xbf\x01\n\rSampleMessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nitem_count\x18\x03 \x01(\x05\x12\x17\n\x06status\x18\x04 \x01(\x0e\x32\x07.Status\x12\x19\n\x0c\x64isplay_name\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0epriority_level\x18\x06 \x01(\x05H\x01\x88\x01\x01\x42\x0f\n\r_display_nameB\x11\n\x0f_priority_level*\\\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n\x0eSTATUS_PENDING\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'sample_message_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_STATUS']._serialized_start = 218
    _globals['_STATUS']._serialized_end = 310
    _globals['_SAMPLEMESSAGE']._serialized_start = 25
    _globals['_SAMPLEMESSAGE']._serialized_end = 216
# @@protoc_insertion_point(module_scope)
