#!/bin/bash

. $TESTSUITE_LIB_UTILS

if [ "x$MYSQL_PORT" = "x" ]; then
    die "MYSQL_PORT must be set"
fi
if [ "x$MYSQL_TMPDIR" = "x" ]; then
    die "MYSQL_TMPDIR must be set"
fi

# Use ramdisk for data if available
RAMDISK=/mnt/ramdisk/$USER
if mkdir -p $RAMDISK 2> /dev/null; then
    MYSQL_BASEDIR=$RAMDISK/_mysql${WORKER_SUFFIX_PATH}
else
    MYSQL_BASEDIR=$MYSQL_TMPDIR
fi
MYSQL_DATADIR=$MYSQL_BASEDIR/data
MYSQL_PIDFILE=$MYSQL_BASEDIR/mysql.pid

MYSQLD=$(which mysqld 2>/dev/null)

if [ "x$MYSQLD" = "x" ]; then
    die "No mysqld binary found, please install mysql-server-core package:

$ sudo apt-get install mysql-server-core-5.7 mysql-client
"
fi

mkdir -p $MYSQL_BASEDIR

run_mysqld() {
    $MYSQLD --datadir="$MYSQL_DATADIR"                  \
            --pid-file="$MYSQL_PIDFILE"                 \
            --log-error="$MYSQL_BASEDIR/mysql.log"      \
            --log-syslog=OFF                            \
            --socket="$MYSQL_BASEDIR/mysql.sock"        \
            --secure-file-priv="$MYSQL_BASEDIR"         \
            --port=$MYSQL_PORT                          \
            --default-storage-engine=INNODB             \
            --character-set-server=UTF8                 \
            "$@"
}

start() {
    $MYSQLD --version
    echo "Testsuite Mysql directory: $MYSQL_BASEDIR"

    rm -rf "$MYSQL_DATADIR"

    run_mysqld --initialize-insecure || die "mysqld initialization failed:

if you see permissions denied error for data directory that may be
caused by AppArmoor rules. Try this:

$ sudo apt-get install apparmor-utils
$ sudo aa-disable /usr/sbin/mysqld
"

    run_mysqld --daemonize || die "mysqld_safe start failed"
}

stop() {
    stop_daemon $MYSQLD $MYSQL_PIDFILE
    rm -rf "$MYSQL_DATADIR"
}

script_main "$@"
