class TraceidManager:
    def __init__(self, trace_id: str, history: set[str]):
        self.trace_id = trace_id
        self._history = history

    def is_testsuite(self, trace_id: str | None) -> bool:
        """Returns True when `trace_id` was generated by testsuite."""
        return trace_id in self._history

    def is_other_test(self, trace_id: str | None) -> bool:
        """Returns True when trace_id was generated in previous tests."""
        if trace_id == self.trace_id:
            return False
        return not self.is_testsuite(trace_id)

