#!/usr/bin/env python3

import argparse
import pathlib
import sys


CHANGELOG_PATH = pathlib.Path('docs/changelog.rst')
CHANGELOG_HEADER = [
    'Changelog',
    '---------',
    '',
]


class Error(Exception):
    pass


def rst_title(string):
    return [string, '~' * len(string)]


def parse_commits(stream):
    result = ['']
    index = 0
    for line in stream:
        line = line.strip()
        if not line:
            continue
        if line.startswith('COMMIT: '):
            if index > 1:
                result.append('')
            index = 0
            continue
        index += 1
        if index == 1:
            line = f'- {line}'
        elif line.startswith('-'):
            line = line[2:].strip()
            line = f'  * {line}'
        else:
            continue
        if index == 2:
            result.append('')
        result.append(line)
    result.append('')
    return result


def parse_changelog():
    lines = CHANGELOG_PATH.read_text().splitlines()
    if lines[:3] != CHANGELOG_HEADER:
        raise Error('Broken changelog header')
    header_end = len(CHANGELOG_HEADER)
    return CHANGELOG_HEADER, lines[header_end:]


def command_new_entry(args):
    new = parse_commits(sys.stdin)
    header, old = parse_changelog()
    changelog = '\n'.join([
        *header, *rst_title(args.version), 'TODO: remove me before saving', *new, *old, ''
    ])
    CHANGELOG_PATH.write_text(changelog)


def main():
    parser = argparse.ArgumentParser()
    parser.set_defaults(handler=None)

    subparsers = parser.add_subparsers(metavar='command', required=True)

    command_parser = subparsers.add_parser(
        'new-entry',
        help='Create new version entry in changelog',
    )
    command_parser.set_defaults(handler=command_new_entry)
    command_parser.add_argument('version')

    args = parser.parse_args()
    try:
        args.handler(args)
    except Error as exc:
        print(f'ERROR: {exc}')
        sys.exit(1)


if __name__ == '__main__':
    main()
