name: Testsuite Linters Tests

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    lint:
        strategy:
            fail-fast: true
            matrix:
                python-version:
                    - "3.10"
                    - "3.13"
                os-version:
                    - "macos-14"
                    - "ubuntu-24.04"
        runs-on: ${{ matrix.os-version }}
        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: ./.github/actions/setup-python
              with:
                  python-version: ${{ matrix.python-version }}
                  with-databases: mongodb,postgresql-binary,redis,mysql,clickhouse,rabbitmq,kafka
            - name: Lint with Ruff
              run: |
                  source ./.venv/bin/activate && make check-linters
            - name: Check formatting with Ruff
              run: |
                  source ./.venv/bin/activate && make check-format
            - name: Check with MyPy
              run: |
                  source ./.venv/bin/activate && make check-mypy
