# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: (Userver) compat tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v2
      - name: clone userver
        run: |
          git clone https://github.com/userver-framework/userver
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip wheel virtualenv pytest
          python -m venv .venv
          .venv/bin/pip install \
            -r requirements-core.txt \
            -r requirements-dev.txt \
            -r userver/testsuite/requirements.txt \
            -r userver/testsuite/requirements-internal-tests.txt
      - name: Run userver testsuite tests
        run: |
          source .venv/bin/activate
          for test_folder in $(find userver/testsuite/tests -mindepth 1 -maxdepth 1 -type d); do
            PYTHONPATH="$(pwd)/userver/testsuite/pytest_plugins/:$PYTHONPATH" pytest $test_folder
          done
      - name: Run mypy for userver testsuite tests
        run: |
          source .venv/bin/activate
          for test_folder in $(find userver/testsuite/tests -mindepth 1 -maxdepth 1 -type d); do
            PYTHONPATH="$(pwd)/userver/testsuite/pytest_plugins/:$PYTHONPATH" mypy $test_folder
          done
      - name: Cleanup
        run: |
          rm -rf userver
